### ISSUE TITLE
TODO: Test out project on Linux

### ISSUE THREAD

**Issue by sebastiandig** [USF-IMARS/mbon_zooplankton_to_dwc#1]
Hi @7yl4r ,

This is a reminder to download and start the project on your local machine.  Currently, this should be run in `Rstudio` and not on the `CLI`.

`Rstudio > File > New Project > Version Control > Git > Repo URL` [obis_zooplankton_setup](https://github.com/sebastiandig/obis_zooplankton_setup/)

TODO: test out download
TODO: @sebastiandig: find a way to force download necessary packages.

Best,
Sebastian

**Comment by 7yl4r** [comment]
The best way I have found to do package setup is to use a DESCRIPTION file and the devtools package. [Here are my notes on it](https://github.com/7yl4r/cheatsheets/blob/master/R.md#project-setup)

**Comment by sebastiandig** [comment]
1. Librarian:
- The message `package librarian required but not installed` is from the using `require()`, but if `FALSE` then it will install in the next line.  Maybe I can suppress this message so that there wouldn't be any confusion. 
2. `bdchecks` may not be necessary at all. This was just a alternate way to check if the required DarwinCore items were in the final dataframe. I can remove it if you think this is not necessary. If you want an example of it's use, I can grab a screenshot for you. 
3. The copying of files may be an issue previously 
- I did some editing of my code that you may need to pull. 
- When I started a new project to show as the "example" for the meeting, I also had issues with copying the data. I made some modifications to [copy_files_from_cloud.R](https://github.com/sebastiandig/obis_zooplankton_setup/blob/main/scripts/copy_files_from_cloud.R) to fix this.  
- Check if your version contains my fix in the function [here](https://github.com/sebastiandig/obis_zooplankton_setup/blob/main/scripts/copy_files_from_cloud.R#L169).
     - If not, let me know and I will look into it further.

**Comment by sebastiandig** [comment]
Actually, after reviewing this, I think the location you set for the `cloud directory` may be wrong, but I have no way of knowing currently. 
- from the error message, it looks like you set it as `/home/tylar/repos/obis_zooplankton_setup/data/metadata`. The location needs to be directed to the box location on your local computer. 
- If this is not the issue, we should talk. I may need to do some more editing.

**Comment by sebastiandig** [comment]
Wait, it might be another issue altogether, relating to creating the file structure. Can you reply with the file structure? 
You can use `fs::dir_tree(type = "directory")`

**Comment by sebastiandig** [comment]
Also, can you show what files it ask to copy over?

**Comment by 7yl4r** [comment]
Revisiting this now and Rstudio is not running any of the chunks. Maybe we can set up a meeting so we can work through this together? My schedule is mostly open: https://bit.ly/ty-calendar

**Comment by sebastiandig** [comment]
Hi Tylar,
Let's meet tomorrow shortly after your meeting tomorrow a little after 2 pm. Send me an email when you can jump on.

**Comment by sebastiandig** [comment]
Hi @7yl4r,

I have updated the code significantly. Hopefully, you'll be able to use this now. Let me know if you would like to meet again about this to test it out and identify issues.
